### ISSUE TITLE
Custom go template function throwing an error 

### ISSUE THREAD

**Issue by pixelsoccupied** [openshift/kube-compare#31]
```
error: template: odfNS.yaml:10:16: executing "storage/odf-external/odfNS.yaml" at <{{template "hello"}}>: template "hello" not defined
```

```
{{define "hello"}}
    hello: world
{{end}}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  annotations:
    workload.openshift.io/allowed: management
    {{ template "hello" }}
  labels:
    openshift.io/cluster-monitoring: "true"
```

It should render instead of the error
```
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage
  annotations:
    workload.openshift.io/allowed: management
    hello: world
  labels:
    openshift.io/cluster-monitoring: "true"
```
