### ISSUE TITLE
What is the significance of .parts.components.type (missing doc i think)

### ISSUE THREAD

**Issue by pixelsoccupied** [openshift/kube-compare#47]
The following seem to give me the same output? (i dont have control-plane-load-kernel-modules.yaml in my cluster)

```
Parts:
  - name: my-part
    Components:
      - name: my-component-1
        type: Optional
        requiredTemplates:
          - control-plane-load-kernel-modules.yaml
Parts:
  - name: my-part
    Components:
      - name: my-component-1
        type: Required
        optionalTemplates:
          - control-plane-load-kernel-modules.yaml
Parts:
  - name: my-part
    Components:
      - name: my-component-1
        requiredTemplates:
          - control-plane-load-kernel-modules.yaml
```
